// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNtJPF9QSI67mJXcPMcyvwBE6DVgv1Ma8',
    appId: '1:571297197212:web:89c901c8d8ca842a259159',
    messagingSenderId: '571297197212',
    projectId: 'to-do-92f42',
    authDomain: 'to-do-92f42.firebaseapp.com',
    storageBucket: 'to-do-92f42.firebasestorage.app',
    measurementId: 'G-CWTFCNG0B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABGIFVB7KhzSORpTtJplNQgtfa-INE2rU',
    appId: '1:571297197212:android:f1350f5aee3121f6259159',
    messagingSenderId: '571297197212',
    projectId: 'to-do-92f42',
    storageBucket: 'to-do-92f42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtkk_NCkaQks6Soe6BHdW14Q8V9vS3Yr8',
    appId: '1:571297197212:ios:56be0e9ecc749ee5259159',
    messagingSenderId: '571297197212',
    projectId: 'to-do-92f42',
    storageBucket: 'to-do-92f42.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtkk_NCkaQks6Soe6BHdW14Q8V9vS3Yr8',
    appId: '1:571297197212:ios:56be0e9ecc749ee5259159',
    messagingSenderId: '571297197212',
    projectId: 'to-do-92f42',
    storageBucket: 'to-do-92f42.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNtJPF9QSI67mJXcPMcyvwBE6DVgv1Ma8',
    appId: '1:571297197212:web:7160132a3fc36169259159',
    messagingSenderId: '571297197212',
    projectId: 'to-do-92f42',
    authDomain: 'to-do-92f42.firebaseapp.com',
    storageBucket: 'to-do-92f42.firebasestorage.app',
    measurementId: 'G-2BK4V2QHPN',
  );
}
